[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "12.13"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
  buildDir = "public"
  filePath = "sitemaps/sitemap.xml"
  prettyURLs = true
