backend:
  name: github
  # change repo to your git repository url
  repo: theifmag/gatsby-blog

site_url: https://www.theifmag.com
display_url: https://www.theifmag.com

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Settings
    files:
      - name: config
        label: Config
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: text
            name: description
            label: Description
            default: ''
            required: false
          - widget: object
            name: home
            label: Homepage Options
            fields:
              - widget: string
                name: title
                label: Title
                default: ''
                required: false
              - widget: markdown
                name: description
                label: Description
                default: ''
                required: false
          - widget: object
            name: socialLinks
            label: Social Links
            fields:
              - widget: string
                name: linkedIn
                label: LinkedIn
                default: ''
                required: false
              - widget: string
                name: twitter
                label: Twitter
                default: ''
                required: false
              - widget: string
                name: facebook
                label: Facebook
                default: ''
                required: false
              - widget: string
                name: email
                label: Email
                default: ''
                required: false
              - widget: string
                name: instagram
                label: Instagram
                default: ''
                required: false

      - name: about
        label: About the Team
        file: /static/assets/about/about-the-team.json
        fields:
          - widget: string
            name: aboutOne
            label: First paragraph
            default: ''
          - widget: string
            name: aboutTwo
            label: Second paragraph
            default: ''
          - widget: string
            name: ourPast
            label: Our Past
            default: ''
          - widget: string
            name: ourPresent
            label: Our Present
            default: ''
          - widget: string
            name: ourFuture
            label: Our Future
            default: ''

          - widget: list
            name: bios
            label: Bios
            allow_add: false
            fields:
              - widget: string
                name: name
                label: Name
                default: ''
              - widget: string
                name: bio
                label: Bio
                default: ''
              - widget: string
                name: linkedin
                label: LinkedIn
                default: ''
              - widget: string
                name: thumbnail
                label: Thumbnail
                default: ''

  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {label: Template, name: template, widget: hidden, default: BlogPost}
      - name: path
        label: Path
        widget: string
        # pattern: [/]
        hint: 'Path must start with /'
      - {name: date, label: Date, widget: datetime}
      - {name: title, label: Title}
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: 'Image size 1280x800 works best :)'
        required: false
        media_library:
          config:
            multiple: false
      - {name: author, label: author, widget: string}
      - label: category
        name: category
        widget: select
        options:
          [
            'Justice & Law',
            'Politics',
            'Health',
            'Economy',
            'Education',
            'Arts & Media',
            'Environment',
            'Violence & Harassment',
            'Casteism',
            'Colorism & Racism',
            'Sports',
            'Podcasts',
            'Opinions & Stories',
            'Rendezvous',
          ]
      - label: "Editor's Choice"
        name: 'EditorChoice'
        widget: 'boolean'
        default: false
      - {
          name: body,
          label: Body,
          widget: markdown,
          hint: '<br> Add this to start a new Para',
        }
